server:
  port: 10086 # 服务端口
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bishe?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 985211
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eurekaserver # eureka的服务名称

eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka